/**
 * The curated phrase bank for curated-prompt mode.
 *
 * A fixed set, shuffled and partitioned at deal time: each player receives a
 * private hand of N phrases, so no phrase reaches two players in the same
 * game. Sized so a realistic room never hits the deal clamp of
 * floor(bankSize / playerCount).
 *
 * Before adding phrases, read ../PROMPT_CRITERIA.md — the selection rules are
 * not recoverable from the accepted phrases alone. Growing the bank is
 * append-only and needs no migration; it is a build-time constant.
 */
export const CURATED_PHRASE_BANK: readonly string[] = [
  "An octopus cooking",
  "A knight fighting a vending machine",
  "A cat conducting an orchestra of mice",
  "A shark knitting",
  "A giraffe in an elevator",
  "A whale wearing a hat",
  "A frog giving a presentation",
  "Bigfoot waiting in line",
  "A crab wielding a sword",
  "A cowboy riding a giant chicken",
  "A seasick pirate",
  "A werewolf getting a haircut",
  "A pug in a cape",
  "A dinosaur reading a newspaper",
  "A knight riding a cat",
  "A goose chasing a mail carrier",
  "Two pandas playing chess",
  "A goldfish with a mustache",
  "A dog reading a book",
  "An elephant in a teacup",
  "A samurai slicing a watermelon",
  "A hamster with a monocle",
  "A walrus in a hammock",
  "A snail on a skateboard",
  "A bear playing a tuba",
  "A crocodile at the dentist",
  "A fish walking a dog",
  "A moose in a phone booth",
  "Two frogs on a seesaw",
  "A squid attacking a rowboat",
  "A cat riding a roomba",
  "A fox playing a banjo",
  "A dragon toasting marshmallows",
  "A skeleton eating spaghetti",
  "A rabbit lifting weights",
  "A T. rex changing a lightbulb",
  "An octopus playing goalie",
  "A spider putting on shoes",
  "A giraffe at a limbo contest",
  "An elephant on a tightrope",
  "A cheetah stuck in traffic",
  "A sloth working as a lifeguard",
  "A pufferfish in a crowded elevator",
  "A hedgehog holding a balloon",
  "A penguin in a sauna",
  "A polar bear with an electric fan",
  "A mole wearing thick glasses",
  "A kangaroo working as a mail carrier",
  "A peacock in a photo booth",
  "An ostrich hiding from a hunter",
  "A mummy at a laundromat",
  "A nun on a motorcycle",
  "A clown at a funeral",
  "A sumo wrestler on a unicycle",
  "A witch vacuuming",
  "Frankenstein's monster threading a needle",
  "An astronaut playing the piano",
  "A pirate typing on a laptop",
  "Santa stuck in a chimney",
  "A camel at a drinking fountain",
  "A hippo in a rowboat",
  "A cheetah on a treadmill",
  "Elvis eating a salad",
  "Abraham Lincoln going through a metal detector",
  "A mime with a bullhorn",
  "The Statue of Liberty lighting a birthday cake with her torch",
  "A viking drinking from a juice box",
  "A surgeon carving a turkey",
  "A judge cracking a nut with his gavel",
  "A superhero riding the bus",
  "Dracula at a tanning salon",
  "Medusa at a hair salon",
  "A cheerleader cheering at a chess match",
  "A whale using a snorkel",
] as const;
